name: GNE Health
favicon: null
layout_spectrum: 0.26268
typography_spectrum: 0.9841127039398998
title: GNE Health
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#414143'
    - '#5a87c2'
    - '#95bce2'
    - '#9c9c9e'
  brandStrength: 0.5269647617824376
  lightness: 0.4006600643042475
  saturation: 0.8649252553004771
  rhythmicContrast: 0.5085608588997275
purpose: []
