name: GNE Health
favicon: null
layout_spectrum: 0.71901366696693
typography_spectrum: 0.9841127039398998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5269647617824376
  lightness: 0.4006600643042475
  saturation: 0.8649252553004771
  rhythmicContrast: 0.5085608588997275
purpose: []
